.\"/*
.\" * Copyright (c) 2017-2019 SUSE LLC.
.\" * All rights reserved
.\" * Authors: Howard Guo, Angela Briel
.\" *
.\" * This program is free software; you can redistribute it and/or
.\" * modify it under the terms of the GNU General Public License
.\" * as published by the Free Software Foundation; either version 2
.\" * of the License, or (at your option) any later version.
.\" *
.\" * This program is distributed in the hope that it will be useful,
.\" * but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" * GNU General Public License for more details.
.\" */
.\"
.TH saptune "8" "March 2019" "" "System Optimisation For SAP"
.SH NAME
saptune \- Comprehensive system optimisation management for SAP solutions

.SH DESCRIPTION
saptune has been improved to much more better adapt the needs of an SAP environment. So at the moment we will support 2 versions of saptune.

We now have our good old version 1 of saptune, which is now deprecated and will be removed with the next release. It's available for compatibility reasons and to give the admin the ability to smoothly migrate his SAP system tunings to the new settings demanded by SAP. To get the man page for the version 1 of saptune please use saptune_v1(8).
To get more information about the migration path from saptune version 1 to saptune version 2 please see saptune-migrate(5)

Our new improved saptune version 2 and the new configuration possibilities and syntax are described in saptuen_v2(8).

.SH SEE ALSO
.NF
saptune-note(5) saptune-migrate(5) saptune_v1(8) saptune_v2(8) tuned(8) tuned-adm(8)

.SH AUTHOR
.NF
Howard Guo <hguo@suse.com>, Angela Briel <abriel@suse.com>
