# .goreleaser.yaml
builds:
  -
    # GOOS list to build for.
    # For more info refer to: https://go.dev/doc/install/source#environment
    #
    # Default: [ 'darwin', 'linux', 'windows' ].
    goos:
      - linux

    # Custom ldflags.
    #
    # Default: '-s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.builtBy=goreleaser'.
    # Templates: allowed.
    ldflags:
      - -X 'github.com/SUSE/saptune/actions.RPMVersion={{.Env.Version}}'
      - -X 'github.com/SUSE/saptune/actions.RPMDate={{.Env.bdate}}'

