#!/bin/bash
# shellcheck disable=SC1004

# saptune update helper script
# upd_helper is called by post script of saptune package installation to
# update the SAP Note name changes between SLE12 and SLE15 in the
# configuration files, saved state files or in the name of the configuration
# files
# only called in postinstallation, if it is a package update
# NOT called, if it is an initial package installation

# upd_helper v1tov2pi
# upd_helper v1tov2pt
# upd_helper sle12to15pt
# upd_helper cleanup
# upd_helper staging

if [ "$1" == "" ]; then
    echo "ERROR: missing argument"
    exit 1
else
    upd_opt="$1"
fi

OLD_SAPTUNE_CONFIG=/var/lib/saptune/config/old_custom_saptune_config
CUSTOM_TUNED_CONF=/etc/tuned/saptune/tuned.conf
SAPTUNE_CONFIG_16=/var/lib/saptune/config/saptune
SAPTUNE_CONFIG_15=/etc/sysconfig/saptune

OVERRIDEDIR=/etc/saptune/override
CUSTOMDIR=/etc/saptune/extra
OLD_SAVEDSTATEDIR=/var/lib/saptune/saved_state
SAVEDSTATEDIR=/run/saptune/saved_state
OLD_PARAMETERSTATEDIR=/var/lib/saptune/parameter
PARAMETERSTATEDIR=/run/saptune/parameter
SECTIONSTATEDIR=/run/saptune/sections

WORKINGAREA=/var/lib/saptune/working
STAGINGAREA=/var/lib/saptune/staging
PACKAGEAREA=/usr/share/saptune

NOTEDIR=/usr/share/saptune/notes
#SOLDIR=/usr/share/saptune/sols
## sles16 installation note == 3565382
## sles16 HANA DB os settings == 3577842
NOTES2CHANGE_15to16="2578899,3565382 2684254,3577842"
#NOTES2CHANGE_12to16="1984787,3565382 2205917,3577842"
NOTES2CHANGE_12to15="1984787,2578899 2205917,2684254"
NOTES2DELETE_16="1771258 1680803 1805750"
NOTES2DELETE_15="1557506 1275776"
SOLS2DELETE_16="SAP-ASE.sol"
FORGOTTEN_NOTES_300="2993054 1656250"

if grep sles:16 /etc/os-release > /dev/null; then
    # SLE16
    SAPTUNE_CONFIG=/var/lib/saptune/config/saptune
    # template - /usr/share/saptune/saptuneTemplate.conf
    NOTES2DELETE=$NOTES2DELETE_16
    NOTES2CHANGE=$NOTES2CHANGE_15to16
    SOLS2DELETE=$SOLS2DELETE_16
    oldVers=15
    newVers=16
else
    SAPTUNE_CONFIG=/etc/sysconfig/saptune
    NOTES2DELETE=$NOTES2DELETE_15
    NOTES2CHANGE=$NOTES2CHANGE_12to15
    SOLS2DELETE=""
    oldVers=12
    newVers=15
fi

update_saptune_config() {
    # SLE16 - update saptune config file
    # add new entries, if not available, no other changes are needed
    # # _STCV1_ is the starting point of SLE16 - for future use
    :
}

update_config() {
    # SLE16 - update saptune config file with new entries, if needed.
    # Do not change existing ones
    # called from the posttrans script of saptune in standard installations
    # or from saptune-helper.service in transactional-updates
    if ! modify; then
        echo "Skip updateConf, will be done later"
        exit 0
    fi
    if [ ! -f $SAPTUNE_CONFIG_16 ]; then
        # saptune config file missing - copy from template
        cp /usr/share/saptune/saptuneTemplate.conf $SAPTUNE_CONFIG_16
    fi
    # update config 12/15 to 16 (special task needed only once!)
    # /var/lib/saptune/config/old_custom_saptune_config is the old
    # /etc/sysconfig/saptune from 12/15
    update_1215_to_16_running_once
    # add new entries, if not available
    update_saptune_config
}

# update config 12/15 to 16 (special task needed only once!)
# /var/lib/saptune/config/old_custom_saptune_config is the old
# /etc/sysconfig/saptune from 12/15
update_1215_to_16_running_once() {
    if [ -f $SAPTUNE_CONFIG_15 ]; then
        # update from 12/15 to 16
        # move old config file away
        mv $SAPTUNE_CONFIG_15 $OLD_SAPTUNE_CONFIG
        param2check="TUNE_FOR_SOLUTIONS TUNE_FOR_NOTES NOTE_APPLY_ORDER STAGING COLOR_SCHEME SKIP_SYSCTL_FILES IGNORE_RELOAD DEBUG TrentoASDP"
        for param in ${param2check}; do
            paramLine=$(grep "^${param}[[:space:]]*=" $OLD_SAPTUNE_CONFIG)
            if [ -n "$paramLine" ]; then
                if grep "^${param}[[:space:]]*=" $SAPTUNE_CONFIG > /dev/null 2>&1; then
                    # change parameter
                    sed -i "s%^${param}[[:space:]]*=.*$%${paramLine}%" $SAPTUNE_CONFIG
                else
                    # append parameter
                    echo -e "\n$paramLine" >> $SAPTUNE_CONFIG
                fi
            fi
        done
        rm -f $OLD_SAPTUNE_CONFIG
    fi
}

set_sysconfig_version() {
    # add or change SAPTUNE_VERSION string in /etc/sysconfig/saptune to "1"
    if (grep "SAPTUNE_VERSION[[:space:]]*=" $SAPTUNE_CONFIG >/dev/null 2>&1); then
        sed -i 's/SAPTUNE_VERSION="[23]"/SAPTUNE_VERSION="1"/' $SAPTUNE_CONFIG
    else
        echo "missing SAPTUNE_VERSION string in $SAPTUNE_CONFIG. Appending ..."
        echo -e "## Type:    string\n## Default: \"3\"\n#\n# Version of saptune\nSAPTUNE_VERSION=\"1\"\n" >> $SAPTUNE_CONFIG
    fi
}

create_tuned_conf() {
    # add 'old' cpu section to tuned.conf for compatibility reasons
    # if a custom tuned.conf file exists, do nothing.
    if [ ! -f $CUSTOM_TUNED_CONF ]; then
        echo "create custom file '$CUSTOM_TUNED_CONF' for compatibility support of saptune version 1"
        echo "see man saptune(8) and saptune-migrate(7) for more information"
        mkdir -p /etc/tuned/saptune
        cp /usr/lib/tuned/saptune/tuned.conf $CUSTOM_TUNED_CONF
        # add description
        sed -i '/^\[main\]/i\
#\
# for compatibility support of saptune version 1 the tuned config script\
# /usr/lib/tuned/saptune/tuned.conf is copied to /etc/tuned/saptune/tuned.conf\
# during the saptune package update from rpm version 1* to version 3*\
# ATTENTION: saptune version 3 (SAPTUNE_VERSION=3 in /etc/sysconfig/saptune)\
# does not use tuned service any longer\
# Please migrate to saptune version 3 as soon as possible\
#\
' $CUSTOM_TUNED_CONF
        # add cpu section
        sed -i '/^\[script\]/i\
[cpu]\
#cpu section added by saptune package installation during package update from version1 to version2\
#stv1tov2#\
governor=performance\
energy_perf_bias=performance\
min_perf_pct=100\
force_latency = 70\
' $CUSTOM_TUNED_CONF
        # use absolute pathname for script
        sed -i 's%script.sh%/usr/lib/tuned/saptune/script.sh%' $CUSTOM_TUNED_CONF
    fi
}

get_back_extra_ASE_BOBJ() {
    # check for extra files needed for the v1tov2 migration
    # get back custom note definition files for BOBJ and/or ASE
    # needed for migration, if customer had applied these notes
    if [ -f "${CUSTOMDIR}"/SAP_BOBJ_n2c.conf ]; then
        mv "${CUSTOMDIR}"/SAP_BOBJ_n2c.conf "${CUSTOMDIR}"/SAP_BOBJ-SAP_Business_OBJects.conf || :
    fi
    if [ -f "${CUSTOMDIR}"/SAP_ASE_n2c.conf ]; then
        mv "${CUSTOMDIR}"/SAP_ASE_n2c.conf "${CUSTOMDIR}"/SAP_ASE-SAP_Adaptive_Server_Enterprise.conf || :
    fi
}

change_note_names() {
    OIFS=$IFS
    #for notepair in $NOTES2CHANGE_12to15; do
    for notepair in $NOTES2CHANGE; do
        IFS=","
        # shellcheck disable=SC2086
        set -- $notepair
        oldNote=$1
        newNote=$2
        IFS=$OIFS
        if [ ! -f ${NOTEDIR}/"${oldNote}" ] && [ -f ${NOTEDIR}/"${newNote}" ]; then
            # the old note definition name is NOT available, but the new one
            # so update from SLE12 to SLE15/SLE15 to SLE16
            # change config

            # 1. change variable TUNE_FOR_NOTES and NOTE_APPLY_ORDER in /etc/sysconfig/saptune
            # " ${oldNote} " or " ${oldNote}\"" or "\"${oldNote}\""
            # srch_pat="[ \"]${oldNote}[ \"]"
            srch_pat1="[ ]${oldNote}[ ]"
            new_pat1=" ${newNote} "
            if grep "$srch_pat1" $SAPTUNE_CONFIG >/dev/null 2>&1; then
                echo "### changing old, SLE${oldVers} specific Note name '$oldNote' to the new, SLE${newVers} Note name '$newNote'"
                sed -i "s/$srch_pat1/$new_pat1/g" $SAPTUNE_CONFIG
            fi
            srch_pat2=" ${oldNote}\""
            new_pat2=" ${newNote}\""
            if grep "$srch_pat2" $SAPTUNE_CONFIG >/dev/null 2>&1; then
                echo "### changing old, SLE${oldVers} specific Note name '$oldNote' to the new, SLE${newVers} Note name '$newNote'"
                sed -i "s/$srch_pat2/$new_pat2/g" $SAPTUNE_CONFIG
            fi
            srch_pat3="\"${oldNote} "
            new_pat3="\"${newNote} "
            if grep "$srch_pat3" $SAPTUNE_CONFIG >/dev/null 2>&1; then
                echo "### changing old, SLE${oldVers} specific Note name '$oldNote' to the new, SLE${newVers} Note name '$newNote'"
                sed -i "s/$srch_pat3/$new_pat3/g" $SAPTUNE_CONFIG
            fi
            srch_pat4="\"${oldNote}\""
            new_pat4="\"${newNote}\""
            if grep "$srch_pat4" $SAPTUNE_CONFIG >/dev/null 2>&1; then
                echo "### changing old, SLE${oldVers} specific Note name '$oldNote' to the new, SLE${newVers} Note name '$newNote'"
                sed -i "s/$srch_pat4/$new_pat4/g" $SAPTUNE_CONFIG
            fi

            # 2. check existence of override file and change name
            if [ -f ${OVERRIDEDIR}/"$oldNote" ]; then
                echo "### mv old override filename '${OVERRIDEDIR}/$oldNote' to new filename '${OVERRIDEDIR}/$newNote'"
                echo "WARNING: the header information in section [version] will NOT be adapted. So it will show the old SAP Note name and the related information"
                mv ${OVERRIDEDIR}/"$oldNote" ${OVERRIDEDIR}/"$newNote"
            fi

            # 3. check existence of saved_state file and change name
            if [ -f ${SAVEDSTATEDIR}/"$oldNote" ]; then
                echo "### mv old saved state file to the new name"
                mv ${SAVEDSTATEDIR}/"$oldNote" ${SAVEDSTATEDIR}/"$newNote"
            fi

            # 4. check, if old note name is available in any parameter saved state file
            srch_pat="\"${oldNote}\""
            new_pat="\"${newNote}\""
            if grep "$srch_pat" "${PARAMETERSTATEDIR}"/* >/dev/null 2>&1; then
                echo "### changing the parameter saved state files"
            fi
            for pfile in "${PARAMETERSTATEDIR}"/*; do
                if grep "$srch_pat" "$pfile" >/dev/null 2>&1; then
                    sed -i "s/$srch_pat/$new_pat/g" "$pfile"
                fi
            done

            # 5. check existence of section state file and change name
            if [ -f ${SECTIONSTATEDIR}/"$oldNote".sections ]; then
                echo "### mv old section state file to the new name"
                mv ${SECTIONSTATEDIR}/"$oldNote".sections ${SECTIONSTATEDIR}/"$newNote".sections
            fi

            # 6. check existence of section state file of enabled solution and
            # change the note names inside the file to allow restart/revert of
            # solution
            esol=$(grep '^TUNE_FOR_SOLUTIONS[[:space:]]*=' $SAPTUNE_CONFIG | awk -F '"' '{ print $2 }')
            if [ -f ${SECTIONSTATEDIR}/"${esol}".sol ]; then
                enabledSol=${SECTIONSTATEDIR}/${esol}.sol
                srch_pat="\"${oldNote}\""
                new_pat="\"${newNote}\""
                if grep "$srch_pat" "${enabledSol}" >/dev/null 2>&1; then
                    echo "### changing note '${oldNote}' to '${newNote}' in solution section file"
                    sed -i "s/$srch_pat/$new_pat/g" "${enabledSol}"
                fi
            fi

            # 7. check custom solutions for using the old note names and change names
            # " ${oldNote} " or " ${oldNote}$" or "^${oldNote} " or "^${oldNote}$"
            # adjust solution files
            for csol in "${CUSTOMDIR}"/*.sol; do
                srch_pat1="[[:space:]]${oldNote}[[:space:]]"
                new_pat1=" ${newNote} "
                if grep "$srch_pat1" "$csol" >/dev/null 2>&1; then
                    echo "### changing old, SLE${oldVers} specific Note name '$oldNote' to the new, SLE${newVers} Note name '$newNote' in custom solution '$csol'"
                    sed -i "s/$srch_pat1/$new_pat1/g" "$csol"
                fi
                srch_pat2="[[:space:]]${oldNote}$"
                new_pat2=" ${newNote}"
                if grep "$srch_pat2" "$csol" >/dev/null 2>&1; then
                    echo "### changing old, SLE${oldVers} specific Note name '$oldNote' to the new, SLE${newVers} Note name '$newNote' in custom solution '$csol'"
                    sed -i "s/$srch_pat2/$new_pat2/g" "$csol"
                fi
                srch_pat3="^${oldNote}[[:space:]]"
                new_pat3="${newNote} "
                if grep "$srch_pat3" "$csol" >/dev/null 2>&1; then
                    echo "### changing old, SLE${oldVers} specific Note name '$oldNote' to the new, SLE${newVers} Note name '$newNote' in custom solution '$csol'"
                    sed -i "s/$srch_pat3/$new_pat3/g" "$csol"
                fi
                srch_pat4="^${oldNote}$"
                new_pat4="${newNote}"
                if grep "$srch_pat4" "$csol" >/dev/null 2>&1; then
                    echo "### changing old, SLE${oldVers} specific Note name '$oldNote' to the new, SLE${newVers} Note name '$newNote' in custom solution '$csol'"
                    sed -i "s/$srch_pat4/$new_pat4/g" "$csol"
                fi
            done

        #else
            # if both note files are available - not possible, rpm should cover
            # if both note files NOT available - not possible, rpm should cover
            # if oldNote is available, but newNote not
            #    still on SLE12, no update from 12 to 15, so nothing to do
        fi
    done
}

enabled_sol_deleted() {
    esol=$(grep '^TUNE_FOR_SOLUTIONS[[:space:]]*=' $SAPTUNE_CONFIG | awk -F '"' '{ print $2 }')
    if [ -n "$esol" ]; then
        # enabled solution found
        for delsol in $SOLS2DELETE; do
            if [ "${esol}.sol" == "$delsol" ]; then
               # enabled solution is deleted
               return 0
            fi
        done
    fi
    return 1
}

delete_sol() {
    esol=$1
    # enabled solution found, which will be deleted
    echo "enabled Solution '$esol' detected, which will be deleted. Adjust config"
    # extract notes of enabled solution from the note definition
    if [ -f ${OVERRIDEDIR}/"${esol}".sol ]; then
        # file found in the override area
        SOLNOTES=$(awk '/\[ArchX86\]/ {getline; print $0}' ${OVERRIDEDIR}/"${esol}".sol)
        echo "WARNING: override file for enabled Solution '${esol}' detected. As this Solution will be no longer available, please remove your override file"
    else
        # file found in the working area
        SOLNOTES=$(awk '/\[ArchX86\]/ {getline; print $0}' ${WORKINGAREA}/sols/"${esol}".sol)
    fi
    # for each note from the solution check, if note is in
    # NOTE_APPLY_ORDER. If not, skip note (do nothing).
    # Else add note to TUNE_FOR_NOTES, if not yet available
    add_TUNE_FOR_NOTES "$SOLNOTES" "$esol" "from deleted"
    # delete solution from TUNE_FOR_SOLUTIONS
    echo "### removing solution '$esol' from TUNE_FOR_SOLUTIONS"
    sed -i "s/$esol//g" $SAPTUNE_CONFIG
    # do nothing for not enabled solution (no need to adjust the config)
}

delete_notes() {
    for delnote in $NOTES2DELETE; do
        if [ ! -f ${NOTEDIR}/"${delnote}" ]; then
            # 1. delete Note from variable TUNE_FOR_NOTES and NOTE_APPLY_ORDER in /etc/sysconfig/saptune
            # " ${delnote} " or " ${delnote}\"" or "\"${delnote}\""
            # srch_pat="[ \"]${delnote}[ \"]"
            srch_pat1="[ ]${delnote}[ ]"
            del_pat1=" "
            if grep "$srch_pat1" $SAPTUNE_CONFIG >/dev/null 2>&1; then
                echo "### removing old, SLE${oldVers} specific Note name '$delnote' from $SAPTUNE_CONFIG"
                sed -i "s/$srch_pat1/$del_pat1/g" $SAPTUNE_CONFIG
            fi
            srch_pat2=" ${delnote}\""
            del_pat2="\""
            if grep "$srch_pat2" $SAPTUNE_CONFIG >/dev/null 2>&1; then
                echo "### removing old, SLE${oldVers} specific Note name '$delnote' from $SAPTUNE_CONFIG"
                sed -i "s/$srch_pat2/$del_pat2/g" $SAPTUNE_CONFIG
            fi
            srch_pat3="\"${delnote} "
            del_pat3="\""
            if grep "$srch_pat3" $SAPTUNE_CONFIG >/dev/null 2>&1; then
                echo "### removing old, SLE${oldVers} specific Note name '$delnote' from $SAPTUNE_CONFIG"
                sed -i "s/$srch_pat3/$del_pat3/g" $SAPTUNE_CONFIG
            fi
            srch_pat4="\"${delnote}\""
            del_pat4="\"\""
            if grep "$srch_pat4" $SAPTUNE_CONFIG >/dev/null 2>&1; then
                echo "### removing old, SLE${oldVers} specific Note name '$delnote' from $SAPTUNE_CONFIG"
                sed -i "s/$srch_pat4/$del_pat4/g" $SAPTUNE_CONFIG
            fi

            # 2. check existence of override file and print a WARNING
            if [ -f ${OVERRIDEDIR}/"$delnote" ]; then
                echo "WARNING: override file '${OVERRIDEDIR}/$delnote' exists, but Note definition is no longer supported."
                echo "Please check and remove superfluous file"
            fi

            # 3. check existence of saved_state file and remove file
            # normally shouldn't be available
            if [ -f ${SAVEDSTATEDIR}/"$delnote" ]; then
                echo "WARNING: old saved state file '${SAVEDSTATEDIR}/$delnote' found, removing superfluous file."
                rm ${SAVEDSTATEDIR}/"$delnote"
            fi

            # 4. check existence of sections state file and remove file
            # normally shouldn't be available
            if [ -f ${SECTIONSTATEDIR}/"$delnote".sections ]; then
                echo "WARNING: old sections state file '${SECTIONSTATEDIR}/${delnote}.sections' found, removing superfluous file."
                rm ${SECTIONSTATEDIR}/"$delnote".sections
            fi
        fi
    done
}

adjust_enabled_solution() {
    # called from the postinstall script of saptune to adjust the notes of an
    # enabled solution
    # need to run before the working area is touched in the postinstall
    # only needed, if staging is NOT active and a solution is enabled and no
    # override file exists.
    # The staging is checked in the postinstall, so no need to do it again.
    # If an override file for the enabled solution exists, we will NOT change
    # anything. It is up to the customer to check and adjust after the update
    esol=$(grep '^TUNE_FOR_SOLUTIONS[[:space:]]*=' $SAPTUNE_CONFIG | awk -F '"' '{ print $2 }')
    if enabled_sol_deleted; then
        # enabled solution found, which will be deleted. Adjust config
        delete_sol "$esol"
        return 0
    fi
    if [ -n "$esol" ] && [ ! -f ${OVERRIDEDIR}/"${esol}".sol ]; then
        # enabled solution found, override does not exist
        # extract notes of enabled solution from the solution definition file
        # only use the first note list (for x86).
        # needs to be changed, if we provide different note lists for
        # Power or Intel for one solution in the future
        echo "detected enabled Solution '$esol', checking for new or deleted Notes"
        if [ -f /var/lib/saptune/.v2_solutions ]; then
            # starting from v2
            # extract old notes of enabled solution from the 'old' solutions file
            OLD_NOTES=$(sed -n "0,/^${esol} = / s///p" /var/lib/saptune/.v2_solutions)
        else
            # starting from v3
            # extract old notes of enabled solution from the note definition
            # file found in the working area
            OLD_NOTES=$(awk '/\[ArchX86\]/ {getline; print $0}' ${WORKINGAREA}/sols/"${esol}".sol)
        fi
        # extract new notes of enabled solution from the note definition file
        # found in the package area
        NEW_NOTES=$(awk '/\[ArchX86\]/ {getline; print $0}' ${PACKAGEAREA}/sols/"${esol}".sol)
        skip_list=${NOTES2CHANGE//,/ }

        # get the new added Notes
        for nnote in $NEW_NOTES; do
            found=false
            for onote in $OLD_NOTES; do
                if [ "$nnote" == "$onote" ]; then
                    found=true
                    break
                fi
            done
            if [ "$found" == "false" ]; then
                # check against skip_list, these notes will resolved later
                for snote in $skip_list; do
                    if [ "$snote" == "$nnote" ]; then
                        found=true
                        break
                    fi
                done
                if [ "$found" == "false" ]; then
                    NOTES2ADD="$NOTES2ADD $nnote"
                fi
            fi
        done
        # get the removed Notes
        for onote in $OLD_NOTES; do
            found=false
            for nnote in $NEW_NOTES; do
                if [ "$onote" == "$nnote" ]; then
                    found=true
                    break
                fi
            done
            if [ "$found" == "false" ]; then
                # check against skip_list, these notes will resolved later
                for snote in $skip_list; do
                    if [ "$snote" == "$onote" ]; then
                        found=true
                        break
                    fi
                done
                if [ "$found" == "false" ]; then
                    NOTES2REM="$NOTES2REM $onote"
                fi
            fi
        done
        add_NOTE_APPLY_ORDER "$NOTES2ADD" "$esol"
        add_TUNE_FOR_NOTES "$NOTES2REM" "$esol" "deleted from"
    fi
    if [ -n "$esol" ] && [ -f ${OVERRIDEDIR}/"${esol}".sol ]; then
        echo "WARNING: override file for enabled Solution '${esol}' detected. As the content of this Solution changed, please check and adapt your override file"
    fi
}

add_NOTE_APPLY_ORDER() {
    new_notes="$1"
    sol="$2"
    apply_list=$(grep '^NOTE_APPLY_ORDER[[:space:]]*=' $SAPTUNE_CONFIG | awk -F '"' '{ print $2 }')
    notes_list=$(grep '^TUNE_FOR_NOTES[[:space:]]*=' $SAPTUNE_CONFIG | awk -F '"' '{ print $2 }')

    for fnote in $new_notes; do
        # check, if fnote is already available in NOTE_APPLY_ORDER
        # if not, append
        found=false
        for anote in $apply_list; do
            if [ "$anote" == "$fnote" ]; then
                found=true
                break
            fi
        done
        if [ "$found" == "false" ]; then
            # append
            echo "### appending the new Note '$fnote' from Solution '$sol' to 'NOTE_APPLY_ORDER' in '$SAPTUNE_CONFIG'"
            sed -i "/^NOTE_APPLY_ORDER[[:space:]]*=.*/s/\"$/ $fnote\"/" $SAPTUNE_CONFIG
        fi

        # delete Note from TUNE_FOR_NOTES, if available.
        delete_TUNE_FOR_NOTES "$fnote" "$sol"
    done
}

add_TUNE_FOR_NOTES() {
    del_notes="$1"
    sol="$2"
    txt="$3"
    apply_list=$(grep '^NOTE_APPLY_ORDER[[:space:]]*=' $SAPTUNE_CONFIG | awk -F '"' '{ print $2 }')

    for fnote in $del_notes; do
        # check, if fnote is already available in NOTE_APPLY_ORDER
        # if no - do nothing, all good
        # if yes - do NOT remove the node from NOTE_APPLY_ORDER, but add
        # note to TUNE_FOR_NOTES
        for dnote in $apply_list; do
            if [ "$dnote" == "$fnote" ]; then
                # don't touch NOTE_APPLY_ORDER, but
                # append Note to TUNE_FOR_NOTES, if not yet available
                append_TUNE_FOR_NOTES "$fnote" "$sol" "$txt"
            fi
        done
    done
}

append_TUNE_FOR_NOTES() {
    # append Note to TUNE_FOR_NOTES, if not yet available.
    notes="$1"
    sol="$2"
    txt="$3"
    notes_list=$(grep '^TUNE_FOR_NOTES[[:space:]]*=' $SAPTUNE_CONFIG | awk -F '"' '{ print $2 }')

    for fnote in $notes; do
        found=false
        for tnote in $notes_list; do
            if [ "$tnote" == "$fnote" ]; then
                found=true
                break
            fi
        done
        if [ "$found" == "false" ]; then
            if [ -n "$sol" ]; then
                echo "### appending the Note '$fnote' $txt Solution '$sol' to 'TUNE_FOR_NOTES' in '$SAPTUNE_CONFIG'"
                sed -i "/^TUNE_FOR_NOTES[[:space:]]*=.*/s/\"$/ $fnote\"/" $SAPTUNE_CONFIG
            #else # for future use
            fi
        fi
    done
}

delete_TUNE_FOR_NOTES() {
    # delete Note from TUNE_FOR_NOTES, if available.
    # " ${delnote} " or " ${delnote}\"" or "\"${delnote} " or "\"${delnote}\""
    notes="$1"
    sol="$2"
    for fnote in $notes; do
        changes=""
        srch_pat1="[ ]${fnote}[ ]"
        del_pat1=" "
        changes+=$(sed -i "/^TUNE_FOR_NOTES[[:space:]]*=.*${fnote}.*/s/$srch_pat1/$del_pat1/g w /dev/stdout" $SAPTUNE_CONFIG)
        srch_pat2=" ${fnote}\""
        del_pat2="\""
        changes+=$(sed -i "/^TUNE_FOR_NOTES[[:space:]]*=.*${fnote}.*/s/$srch_pat2/$del_pat2/g w /dev/stdout" $SAPTUNE_CONFIG)
        srch_pat3="\"${fnote} "
        del_pat3="\""
        changes+=$(sed -i "/^TUNE_FOR_NOTES[[:space:]]*=.*${fnote}.*/s/$srch_pat3/$del_pat3/g w /dev/stdout" $SAPTUNE_CONFIG)
        srch_pat4="\"${fnote}\""
        del_pat4="\"\""
        changes+=$(sed -i "/^TUNE_FOR_NOTES[[:space:]]*=.*${fnote}.*/s/$srch_pat4/$del_pat4/g w /dev/stdout" $SAPTUNE_CONFIG)
        if [ -n "$changes" ]; then
            if [ -n "$sol" ]; then
                echo "### removing Note '$fnote' from 'TUNE_FOR_NOTES' in '$SAPTUNE_CONFIG' as it is now part of the enabled Solution '$sol'"
            else
                # for future use, will need some 'fine tuning'
                echo "### removing Note '$fnote' from 'TUNE_FOR_NOTES' in '$SAPTUNE_CONFIG' as it is no longer shipped with saptune"
            fi
        fi
    done
}

fix_300() {
    # called from the postinstall script of saptune to fix a bug special in
    # version 3.0.0
    esol=$(grep '^TUNE_FOR_SOLUTIONS[[:space:]]*=' $SAPTUNE_CONFIG | awk -F '"' '{ print $2 }')
    if [ -n "$esol" ]; then
        if [ "$esol" == "NETWEAVER" ] || [ "$esol" == "S4HANA-APPSERVER" ]; then
            FORGOTTEN_NOTES_300="$FORGOTTEN_NOTES_300 900929"
        fi
        add_NOTE_APPLY_ORDER "$FORGOTTEN_NOTES_300" "$esol"
    fi
}

setup_workingarea() {
    # handling of working area is the same for initial install or update
    # initial install or update from v1 or v2 - STAGING is 'false' by default
    # the entire content of package area gets copied directly to the working
    # area which is empty at that state.
    # update from v3 or later - STAGING may be 'true'
    if ! modify; then
        echo "Skip setup_workingarea, will be done later"
        exit 0
    fi
    staging=$(grep '^STAGING=' $SAPTUNE_CONFIG | awk -F '"' '{ print $2 }')
    if [ "$staging" == "true" ]; then
        # handle staging area and DON'T touch the working area
        # done later with 'upd_helper staging'
        exit 0
    fi
    # staging is NOT active, same behavior as with v2
    # adjust the notes of an enabled solution, if needed
    adjust_enabled_solution
    if [ -f /var/lib/saptune/.v2_solutions ]; then
        # remove no longer needed old solution definition file
        rm -f /var/lib/saptune/.v2_solutions
    fi

    # set up working area
    if [ -d /var/lib/saptune/working/notes ] || [ -d /var/lib/saptune/working/sols ]; then
        rm -rf /var/lib/saptune/working/*
    fi
    mkdir -p /var/lib/saptune/working/notes
    cp /usr/share/saptune/notes/* /var/lib/saptune/working/notes
    mkdir -p /var/lib/saptune/working/sols
    cp /usr/share/saptune/sols/* /var/lib/saptune/working/sols
    # clean up of working area no longer needed, because function was
    # moved from postinstall to posttrans, which means package area
    # only contains notes/solutions from the new package version
    # files from old package version are already removed
}

cleanup_savestates() {
    # cleanup older, no longer handled savedState files
    param_filelist="/var/lib/saptune/parameter/IO_SCHEDULER_sr*"
    for i in $param_filelist ; do
        [ -f "$i" ] && rm -f "$i"
    done
    sle_vers=$(sed -n "s%.*baseversion>\(.*\)</base.*%\1%p" /etc/products.d/baseproduct)
    [[ $sle_vers != 12 ]] && rm -f /var/lib/saptune/parameter/UserTasksMax
    [[ $sle_vers != 12 ]] && rm -f /etc/systemd/logind.conf.d/saptune-UserTasksMax.conf

    # move saved state files to /run
    if [ ! -d /run/saptune ]; then
        mkdir -p /run/saptune
    fi
    if [ -d "$OLD_PARAMETERSTATEDIR" ]; then
        mv "$OLD_PARAMETERSTATEDIR" "$PARAMETERSTATEDIR"
    fi
    if [ -d "$OLD_SAVEDSTATEDIR" ]; then
        mv "$OLD_SAVEDSTATEDIR" "$SAVEDSTATEDIR"
    fi
}

update_stagingarea() {
    # called from the posttrans script of saptune to handle the staging area
    # check for changed or new notes
    if ! modify; then
        echo "Skip update_stagingarea, will be done later"
        exit 0
    fi
    staging=$(grep '^STAGING=' $SAPTUNE_CONFIG | awk -F '"' '{ print $2 }')
    if [ "$staging" != "true" ]; then
        exit 0
    fi
    for pnote in "${PACKAGEAREA}"/notes/*; do
        note=${pnote##*/}
        if [ -f ${WORKINGAREA}/notes/"${note}" ]; then
            md5_packed_note=$(/usr/bin/md5sum "$pnote" | awk '{print $1}')
            md5_working_note=$(/usr/bin/md5sum ${WORKINGAREA}/notes/"${note}" | awk '{print $1}')
            # check for unchanged notes
            if [ "$md5_packed_note" == "$md5_working_note" ]; then
                # ignore unchanged notes
                continue
            fi
            # check for changed notes
            if [ "$md5_packed_note" != "$md5_working_note" ]; then
                # copy changed note from package area to staging area
                cp "$pnote" ${STAGINGAREA}/latest
            fi
        else
            # found new note
            # copy new note from package area to staging area
            cp "$pnote" ${STAGINGAREA}/latest
        fi
    done
    # check for deleted notes
    # available in working area but not in package area
    for wnote in "${WORKINGAREA}"/notes/*; do
        note=${wnote##*/}
        if [ ! -f ${PACKAGEAREA}/notes/"${note}" ]; then
            # note deleted in the current installed package
            # create a note file in staging area, which only contains the
            # version information of the 'old' note
            # as a flag for a later removal from the working area
            awk '/\[version\]/ {
                print $0
                while (getline > 0) {
                    if ($1 ~ /\[/) { exit }
                    print $0
                }
            }' "${wnote}" > ${STAGINGAREA}/latest/"${note}"
        fi
    done
    # check for changed or new solutions
    for psol in "${PACKAGEAREA}"/sols/*; do
        sol=${psol##*/}
        if [ -f ${WORKINGAREA}/sols/"${sol}" ]; then
            md5_packed_sol=$(/usr/bin/md5sum "$psol" | awk '{print $1}')
            md5_working_sol=$(/usr/bin/md5sum ${WORKINGAREA}/sols/"${sol}" | awk '{print $1}')
            # check for unchanged solutions
            if [ "$md5_packed_sol" == "$md5_working_sol" ]; then
                # ignore unchanged solution
                continue
            fi
            # check for changed solutions
            if [ "$md5_packed_sol" != "$md5_working_sol" ]; then
                # copy changed solution from package area to staging area
                cp "$psol" ${STAGINGAREA}/latest
            fi
        else
            # found new solution
            # copy new solution from package area to staging area
            cp "$psol" ${STAGINGAREA}/latest
        fi
    done
    # check for deleted solutions
    # available in working area but not in package area
    for wsol in "${WORKINGAREA}"/sols/*; do
        sol=${wsol##*/}
        if [ ! -f ${PACKAGEAREA}/sols/"${sol}" ]; then
            # solution deleted in the current installed package
            # create a solution file in staging area, which only contains the
            # version information of the 'old' solution
            # as a flag for a later removal from the working area
            awk '/\[version\]/ {
                print $0
                while (getline > 0) {
                    if ($1 ~ /\[/) { exit }
                    print $0
                }
            }' "${wsol}" > ${STAGINGAREA}/latest/"${sol}"
        fi
    done
}

create_dirs() {
    if ! modify; then
        echo "Skip createDirs, will be done later"
        exit 0
    fi
    # saptune config location
    mkdir -p /var/lib/saptune/config
    # working and staging location
    mkdir -p /var/lib/saptune/working
    mkdir -p /var/lib/saptune/staging/latest
    # logdir
    mkdir -p /var/log/saptune
}

# SLE16 base tuning
set_base_tuning() {
    if ! modify; then
        echo "Skip baseTuning, will be done later"
        exit 0
    fi
    if immutable; then
        if [ -f /etc/saptune/.baseTuning ]; then
            echo "enable saptune base tuning - enable SAP_Base solution"
            sed -i 's/TUNE_FOR_SOLUTIONS=".*$/TUNE_FOR_SOLUTIONS="SAP_Base"/' $SAPTUNE_CONFIG
            sed -i 's/TUNE_FOR_NOTES=".*$/TUNE_FOR_NOTES=""/' $SAPTUNE_CONFIG
            sed -i 's/NOTE_APPLY_ORDER=".*$/NOTE_APPLY_ORDER="1275776"/' $SAPTUNE_CONFIG
        fi
    else
        if /usr/bin/systemd-detect-virt -q -r >/dev/null 2>&1; then
            # systemctl and saptune will not work in chroot env
            echo "enable saptune base tuning - enable SAP_Base solution"
            sed -i 's/TUNE_FOR_SOLUTIONS=".*$/TUNE_FOR_SOLUTIONS="SAP_Base"/' $SAPTUNE_CONFIG
            sed -i 's/TUNE_FOR_NOTES=".*$/TUNE_FOR_NOTES=""/' $SAPTUNE_CONFIG
            sed -i 's/NOTE_APPLY_ORDER=".*$/NOTE_APPLY_ORDER="1275776"/' $SAPTUNE_CONFIG
        else
            echo "activate saptune base tuning - apply SAP_Base solution"
            /usr/bin/systemctl start saptune.service
            /usr/sbin/saptune solution apply SAP_Base >/dev/null 2>&1
        fi
    fi
    rm -f /etc/saptune/.baseTuning
}

immutable() {
    if [ -x /usr/sbin/transactional-update ]; then
        return 0
    fi
    return 1
}

roRoot() {
    if (grep ".*[[:space:]]/[[:space:]].*[[:space:]]ro[[:space:],]" /proc/mounts >/dev/null 2>&1); then
        return 0
    fi
    return 1
}

modify() {
    if immutable && ! roRoot; then
        # immutable system in transactional update
        # do NOT write to /var, postpone to systemd service file during boot
        return 1
    fi
    return 0
}

case "$upd_opt" in
v1tov2pi)
    # called from the postinstall script of saptune, if installation was an
    # update from saptune version 1 to version 2/3. For SLE12/15 only
    set_sysconfig_version
    create_tuned_conf
    ;;
v1tov2pt)
    # called from the posttrans script of saptune, if installation was an
    # update from saptune version 1 to version 2/3. For SLE12/15 only
    get_back_extra_ASE_BOBJ
    ;;
cleanup)
    # called from the postinstall script of saptune to clean up some leftover
    # files from older saptune operations. For SLE12/15 only
    cleanup_savestates
    ;;
fix_300)
    # called from the postinstall script of saptune to fix a bug special in
    # version 3.0.0. For SLE12/15 only
    fix_300
    ;;
sle12to15pt)
    # called from the posttrans script of saptune, if installation was an
    # update from saptune version 2/3 to version 2/3. For SLE12/15 only
    change_note_names
    delete_notes
    ;;
sleto16pt)
    # called from the posttrans script of saptune
    # update 12/15 to 16 or update from 16 to 16
    # important for note delete, sol delete and note changes in sols
    # needs to run always
    if ! modify; then
        echo "Skip sleto16pt, will be done later"
        exit 0
    fi
    change_note_names
    delete_notes
    ;;
baseTuning)
    # SLE16 base tuning
    # called from posttrans script of saptune
    set_base_tuning
    ;;
setup_workingarea)
    # called from the posttrans script of saptune to handle the working area
    setup_workingarea
    ;;
staging)
    # called from the posttrans script of saptune to handle the staging area
    update_stagingarea
    ;;
updateConf)
    # SLE16 - update saptune config file with new entries, if needed.
    # Do not change existing ones
    # update config 12/15 to 16 (special task needed only once!)
    # called from the postinstall script of saptune in standard installations
    # or from saptune-helper.service in transactional-updates
    update_config
    ;;
dropHelperSvc)
    # if in tu cp /usr/share/saptune/scripts/upd_helper_svc /etc/saptune
    # called in postinstall script of saptune
    if immutable; then
        cp /usr/share/saptune/scripts/upd_helper_svc /etc/saptune
        #ln -s /usr/lib/systemd/system/saptune_helper.service /etc/systemd/system/sysinit.target.wants
    fi
    ;;
createDirs)
    # create directories in /var
    # called in postinstall script of saptune
    create_dirs
    ;;
esac
