name: Saptune Github Release

on:
  push:
    tags:
      - '*'

permissions:
  contents: write
  packages: write

jobs:
  Create_artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Pull the Container Image
        run: docker pull registry.opensuse.org/home/angelabriel/st-ci-base/containers/st-ci-base:latest

      - name: Run Container Image
        run: docker run --name saptune-release --privileged --tmpfs /run -v /sys/fs/cgroup:/sys/fs/cgroup:rw --cgroupns=host -td -v "${{ github.workspace }}:/app" -e bdate=$(date +'%Y-%m-%d') -e Version=${{ github.ref_name }} -e GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} registry.opensuse.org/home/angelabriel/st-ci-base/containers/st-ci-base:latest

      - name: Run goreleaser release
        run: docker exec -t saptune-release /bin/sh -c "cd /app; ./run_saptune_goreleaser.sh;"
